definitions:
  users.UserResponseDto:
    properties:
      age:
        type: integer
      firstName:
        type: string
      gender:
        type: string
      id:
        type: string
      lastName:
        type: string
      nationality:
        type: string
      secondName:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Effective Mobile test task in Gin Framework
  title: Swagger Documentation
  version: "1.0"
paths:
  /health:
    get:
      description: Checking health of backend
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health Check
  /users:
    get:
      description: Endpoint for getting all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/users.UserResponseDto'
            type: array
      summary: All users
    post:
      description: Endpoint for creating and saving user to database
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/users.UserResponseDto'
      summary: Create user
  /users/{id}:
    get:
      description: Endpoint for getting user with exact id
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.UserResponseDto'
      summary: The exact user
  /users/health:
    get:
      description: Checking health of users endpoint
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Users Endpoint Health Check
swagger: "2.0"
