definitions:
  users.User:
    properties:
      firstName:
        type: string
      lastName:
        type: string
      secondName:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Effective Mobile test task in Gin Framework
  title: Swagger Documentation
  version: "1.0"
paths:
  /health:
    get:
      description: Checking health of backend
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health Check
  /nasa:
    get:
      description: Endpoint for getting the whole album
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/users.User'
            type: array
      summary: The whole album
  /nasa/{date}:
    get:
      description: Endpoint for getting the APOD with exact date
      parameters:
      - description: Date
        in: path
        name: date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.User'
      summary: The exact APOD
  /nasa/health:
    get:
      description: Checking health of nasa endpoint
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Nasa Endpoint Health Check
  /users:
    post:
      description: Endpoint for creating and saving user to database
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/users.User'
      summary: Create user
swagger: "2.0"
